CREATE TABLE Account
(
	Id SERIAL PRIMARY KEY,
	Login CHARACTER VARYING(30) NOT NULL UNIQUE,
	Passwords CHARACTER VARYING(30) NOT NULL 
);
CREATE TABLE TypeDessert
(
	Id SERIAL PRIMARY KEY,
	TypeName CHARACTER VARYING(30) NOT NULL
);
CREATE TABLE Confections
(
	Id SERIAL PRIMARY KEY,
	Name CHARACTER VARYING(30) NOT NULL,
	Surname CHARACTER VARYING(30) NOT NULL,
	Patronomic CHARACTER VARYING(30) NOT NULL,
	AccountId INTEGER NOT NULL,
	TypeDessertId INTEGER NOT NULL,
	FOREIGN KEY (TypeDessertId) REFERENCES TypeDessert(Id),
	FOREIGN KEY (AccountId) REFERENCES Account (Id)
);
CREATE TABLE Dessert
(
	Id SERIAL PRIMARY KEY,
	Name CHARACTER VARYING(30) NOT NULL,
	TypeDessertId INTEGER NOT NULL,
	ConfectionsId INTEGER NOT NULL,
	FOREIGN KEY (ConfectionsId) REFERENCES Confections (Id),
	FOREIGN KEY (TypeDessertId) REFERENCES TypeDessert (Id)
);
CREATE TABLE Basket
(
	Id SERIAL PRIMARY KEY,
	CountOrder INTEGER NOT NULL
);
CREATE TABLE Orders
(
	Id SERIAL PRIMARY KEY,
	DessertId INTEGER NOT NULL,
	BasketId INTEGER NOT NULL,
	Prices INTEGER NOT NULL,
	StateOrder CHARACTER VARYING(30) NOT NULL,
	FOREIGN KEY (DessertId) REFERENCES Dessert (Id),
	FOREIGN KEY (BasketId) REFERENCES Basket (Id)
);
CREATE TABLE Customers
(
	Id SERIAL PRIMARY KEY,
	Name CHARACTER VARYING(30) NOT NULL,
	Surname CHARACTER VARYING(30) NOT NULL,
	Patronomic CHARACTER VARYING(30) NOT NULL,
	BasketId INTEGER NOT NULL,
	AccountId INTEGER NOT NULL,
	FOREIGN KEY (AccountId) REFERENCES Account (Id),
	FOREIGN KEY (BasketId) REFERENCES Basket (Id)
);
CREATE TABLE Reviews
(
	Id SERIAL PRIMARY KEY,
	CustomerId INTEGER NOT NULL,
	Reviews CHARACTER VARYING(150) NOT NULL,
	OrdersId INTEGER NOT NULL,
	FOREIGN KEY (OrdersId) REFERENCES Orders (Id),
	FOREIGN KEY (CustomerId) REFERENCES Customers (Id)
);
CREATE TABLE Delivery
(
	Id SERIAL PRIMARY KEY,
	OrderId INTEGER NOT NULL,
	City CHARACTER VARYING(30) NOT NULL,
	Street CHARACTER VARYING(30) NOT NULL,
	NumberHome INTEGER NOT NULL,
	FOREIGN KEY (OrderId) REFERENCES Orders (Id)
);
CREATE TABLE Ingredient
(
	Id SERIAL PRIMARY KEY,
	Name CHARACTER VARYING(30) NOT NULL,
	Squirrels INTEGER NOT NULL,
	Fats INTEGER NOT NULL,
	Carbohydrates INTEGER NOT NULL
);
CREATE TABLE Ingredients
(
	Id SERIAL PRIMARY KEY,
	IngredientId INTEGER NOT NULL,
	DessertId INTEGER NOT NULL,
	FOREIGN KEY (IngredientId) REFERENCES Ingredient (Id),
	FOREIGN KEY (DessertId) REFERENCES Dessert (Id)
);
